### ISSUE TITLE
Doble items

### ISSUE THREAD

**Issue by Javier81963** [danjono/Inventory-Rollback#25]
Idk why, but the plugin duplicates items when the users join in, its no error in the console

**Comment by danjono** [comment]
I'm going to assume you mean it does two backups instead of one when a player joins instead of it duplicating items for the player.

It doesn't do this by default so it must be a conflicting plugin. Inventory Rollback listens to the [PlayerJoinEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerJoinEvent.html) and logs whenever that is fired. There must be another plugin you have running that for whatever reasons makes the event fire twice causing duplicate backups.

Are you able to provide any more information about your setup or if you have any ideas yourself what could be causing it?

**Comment by Javier81963** [comment]
Im so sorry, it was another plugin, not yours, thank you for answer me
